server.servlet.context-path=/kotlin-spring

spring.application.name=demo
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/demo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jackson.serialization-inclusion=non-null

jwt.secret=nscN1dNJ5Qvy8V/Stw7dxvjPWM3Iey2feUoo2RnWakQ=
jwt.expiration=86400000
