### @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

> {%
    client.global.set("token", response.body.token);
%}
